name: Create GitHub release when a tag is pushed

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.14.7'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Generate changelog
        uses: orhun/git-cliff-action@a9a95522b26fe6403f7bb24031f21fb573d0f5ff # v4
        with:
          args: -vv --latest --strip all

      - name: Create release
        run: gh release create ${{ github.ref_name }} -F git-cliff/CHANGELOG.md dist/*
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
